# Exploration

This is an exploratory notebook where I just attempt to load and explore the data provided in the public repository. I then compute the new columns that I would want as more explanatory statistics for the data.

In [7]:
import pandas as pd
import numpy as np
from datetime import date

In [8]:
case_data = pd.read_csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_malaysia.csv")
test_data = pd.read_csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/tests_malaysia.csv")

diff = len(test_data) - len(case_data)

test_data = test_data.drop(test_data.index[:diff])
test_data = test_data.reset_index()

print(test_data)
print(case_data)

     index        date  rtk-ag    pcr
0       52  2020-03-16       0   2468
1       53  2020-03-17       0   2927
2       54  2020-03-18       0   3411
3       55  2020-03-19       0   3304
4       56  2020-03-20       0   3635
..     ...         ...     ...    ...
497    549  2021-07-26   91233  57972
498    550  2021-07-27   84147  70425
499    551  2021-07-28   77798  73500
500    552  2021-07-29   79001  80399
501    553  2021-07-30   72807  81791

[502 rows x 4 columns]
           date  cases_new  cluster_import  cluster_religious  \
0    2020-03-16        553             NaN                NaN
1    2020-03-17        120             NaN                NaN
2    2020-03-18        117             NaN                NaN
3    2020-03-19        110             NaN                NaN
4    2020-03-20        130             NaN                NaN
..          ...        ...             ...                ...
497  2021-07-26      14516             0.0                7.0
498  2021-07-27      16117             0.0                1.0
499  2021-07-28      17405             0.0                6.0
500  2021-07-29      17170             0.0                2.0
501  2021-07-30      16840             0.0                5.0

     cluster_community  cluster_highRisk  cluster_education  \
0                  NaN               NaN                NaN
1                  NaN               NaN                NaN
2                  NaN               NaN                NaN
3                  NaN               NaN                NaN
4                  NaN               NaN                NaN
..                 ...               ...                ...
497              559.0              57.0               19.0
498              619.0              90.0               30.0
499              621.0             125.0               25.0
500              567.0              77.0               19.0
501              822.0              84.0                9.0

     cluster_detentionCentre  cluster_workplace
0                        NaN                NaN
1                        NaN                NaN
2                        NaN                NaN
3                        NaN                NaN
4                        NaN                NaN
..                       ...                ...
497                     29.0             1504.0
498                     95.0             1365.0
499                     74.0             1580.0
500                    266.0              968.0
501                     61.0             1569.0

[502 rows x 9 columns]

In [9]:
total_testing = test_data["pcr"] + test_data["rtk-ag"]
total_cases = case_data["cases_new"]
dates = test_data["date"]

case_test_ratio = (total_cases / total_testing).round(5)

frame = {"date": dates, "total_testing": total_testing, "total_cases": total_cases, "case_test_ratio": case_test_ratio}

new_df = pd.DataFrame(frame)
new_df

           date  total_testing  total_cases  case_test_ratio
0    2020-03-16           2468          553          0.22407
1    2020-03-17           2927          120          0.04100
2    2020-03-18           3411          117          0.03430
3    2020-03-19           3304          110          0.03329
4    2020-03-20           3635          130          0.03576
..          ...            ...          ...              ...
497  2021-07-26         149205        14516          0.09729
498  2021-07-27         154572        16117          0.10427
499  2021-07-28         151298        17405          0.11504
500  2021-07-29         159400        17170          0.10772
501  2021-07-30         154598        16840          0.10893

[502 rows x 4 columns]